### ISSUE TITLE
Add countdown timer program 

### ISSUE THREAD

**Issue by vaishnaowankar** [Bhavya1912/Hacktober2k22#65]

**Comment by monikluthra** [comment]
import time

def countdown(time_sec):
    while time_sec:
        mins, secs = divmod(time_sec, 60)
        timeformat = '{:02d}:{:02d}'.format(mins, secs)
        print(timeformat, end='\r')
        time.sleep(1)
        time_sec -= 1

    print("stop")

countdown(5)
